'use client';
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Navbar = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const Navbar = () => {
    return ((0, jsx_runtime_1.jsx)("header", { className: "sticky top-0 z-50 glass-panel border-b border-gray-800", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-600 via-purple-600 to-pink-500 flex items-center justify-center shadow-lg shadow-indigo-500/20", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, { className: "w-5 h-5 text-white" }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("span", { className: "text-xl font-bold tracking-tight text-white flex items-center gap-1.5", children: ["StyleSeek ", (0, jsx_runtime_1.jsx)("span", { className: "text-gradient", children: "AI" })] }), (0, jsx_runtime_1.jsx)("span", { className: "block text-[10px] text-gray-400 font-medium tracking-wider uppercase", children: "Powered by Amazon Bedrock & Nova" })] })] }), (0, jsx_runtime_1.jsxs)("nav", { className: "hidden md:flex items-center gap-8 text-sm font-medium text-gray-300", children: [(0, jsx_runtime_1.jsxs)("a", { href: "#assistant", className: "hover:text-indigo-400 transition-colors flex items-center gap-1.5", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, { className: "w-4 h-4 text-indigo-400" }), "AI Assistant"] }), (0, jsx_runtime_1.jsxs)("a", { href: "#catalogue", className: "hover:text-indigo-400 transition-colors flex items-center gap-1.5", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ShoppingBag, { className: "w-4 h-4 text-purple-400" }), "Collection"] }), (0, jsx_runtime_1.jsxs)("a", { href: "#architecture", className: "hover:text-indigo-400 transition-colors flex items-center gap-1.5", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Cpu, { className: "w-4 h-4 text-pink-400" }), "AWS Tech Stack"] })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex items-center gap-3", children: (0, jsx_runtime_1.jsxs)("a", { href: "#assistant", className: "px-4 py-2 text-xs font-semibold rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-all shadow-md shadow-indigo-600/30 flex items-center gap-1.5", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, { className: "w-3.5 h-3.5" }), "Try Assistant"] }) })] }) }));
};
exports.Navbar = Navbar;
//# sourceMappingURL=Navbar.js.map